version: "3"

services:
  db:
    image: postgres:13.5-alpine
    container_name: db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - PGUSER=${DB_USER}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - TZ=UTC
      - PGTZ=UTC
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD", "pg_isready -U admin" ]
      interval: 10s
      timeout: 2s
      retries: 3
    restart: unless-stopped
    networks:
      - network

networks:
  network:
    driver: bridge
