// Code generated by MockGen. DO NOT EDIT.
// Source: ./access.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/vfilipovsky/url-shortener/internal/entity"
)

// MockAccess is a mock of Access interface.
type MockAccess struct {
	ctrl     *gomock.Controller
	recorder *MockAccessMockRecorder
}

// MockAccessMockRecorder is the mock recorder for MockAccess.
type MockAccessMockRecorder struct {
	mock *MockAccess
}

// NewMockAccess creates a new mock instance.
func NewMockAccess(ctrl *gomock.Controller) *MockAccess {
	mock := &MockAccess{ctrl: ctrl}
	mock.recorder = &MockAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccess) EXPECT() *MockAccessMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccess) Create(access *entity.Access) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", access)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAccessMockRecorder) Create(access interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccess)(nil).Create), access)
}

// FindByToken mocks base method.
func (m *MockAccess) FindByToken(token string) (*entity.Access, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByToken", token)
	ret0, _ := ret[0].(*entity.Access)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByToken indicates an expected call of FindByToken.
func (mr *MockAccessMockRecorder) FindByToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByToken", reflect.TypeOf((*MockAccess)(nil).FindByToken), token)
}
