// Code generated by MockGen. DO NOT EDIT.
// Source: ./delete_url.go

// Package mock_url is a generated GoMock package.
package mock_url

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDelete is a mock of Delete interface.
type MockDelete struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteMockRecorder
}

// MockDeleteMockRecorder is the mock recorder for MockDelete.
type MockDeleteMockRecorder struct {
	mock *MockDelete
}

// NewMockDelete creates a new mock instance.
func NewMockDelete(ctrl *gomock.Controller) *MockDelete {
	mock := &MockDelete{ctrl: ctrl}
	mock.recorder = &MockDeleteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDelete) EXPECT() *MockDeleteMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockDelete) Run(code, accessToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", code, accessToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockDeleteMockRecorder) Run(code, accessToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockDelete)(nil).Run), code, accessToken)
}
