// Code generated by MockGen. DO NOT EDIT.
// Source: ./get_url.go

// Package mock_url is a generated GoMock package.
package mock_url

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGet is a mock of Get interface.
type MockGet struct {
	ctrl     *gomock.Controller
	recorder *MockGetMockRecorder
}

// MockGetMockRecorder is the mock recorder for MockGet.
type MockGetMockRecorder struct {
	mock *MockGet
}

// NewMockGet creates a new mock instance.
func NewMockGet(ctrl *gomock.Controller) *MockGet {
	mock := &MockGet{ctrl: ctrl}
	mock.recorder = &MockGetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGet) EXPECT() *MockGetMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockGet) Run(pin, code string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", pin, code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockGetMockRecorder) Run(pin, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockGet)(nil).Run), pin, code)
}
